version: '2.4'
services:
  db:
    image: mysql
    container_name: jpa_ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - jpa_ecommerce:/var/lib/mysql

volumes:
  jpa_ecommerce: